//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentBookdbEntities2 : DbContext
    {
        public RentBookdbEntities2()
            : base("name=RentBookdbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<BookCase> BookCase { get; set; }
        public virtual DbSet<BookCaseBooks> BookCaseBooks { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BooksAuthor> BooksAuthor { get; set; }
        public virtual DbSet<BooksChapters> BooksChapters { get; set; }
        public virtual DbSet<BooksFiles> BooksFiles { get; set; }
        public virtual DbSet<BooksMessage> BooksMessage { get; set; }
        public virtual DbSet<BooksTags> BooksTags { get; set; }
        public virtual DbSet<BooksWishlist> BooksWishlist { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberAddDetail> MemberAddDetail { get; set; }
        public virtual DbSet<MemberDonateAuthor> MemberDonateAuthor { get; set; }
        public virtual DbSet<MemberShopDetail> MemberShopDetail { get; set; }
        public virtual DbSet<Publishing> Publishing { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleFunction> RoleFunction { get; set; }
        public virtual DbSet<SystemAccount> SystemAccount { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
    }
}
