//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public string a_id { get; set; }
        public string a_Name { get; set; }
        public string a_Image { get; set; }
        public Nullable<System.DateTime> a_Birth { get; set; }
        public Nullable<int> a_Point { get; set; }
        public string a_Email { get; set; }
    }
}
