//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksWishlist
    {
        public int bw_id { get; set; }
        public Nullable<int> bc_id { get; set; }
        public string b_id { get; set; }
        public Nullable<System.DateTime> bw_AddTime { get; set; }
    }
}
