//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string m_id { get; set; }
        public string m_Name { get; set; }
        public Nullable<System.DateTime> m_Birth { get; set; }
        public string m_Gender { get; set; }
        public Nullable<int> m_Point { get; set; }
        public string m_Email { get; set; }
        public string m_Image { get; set; }
        public Nullable<System.DateTime> m_RegisterDate { get; set; }
        public Nullable<System.DateTime> m_LastLogin { get; set; }
        public Nullable<System.DateTime> m_LastLogon { get; set; }
        public Nullable<System.DateTime> m_OnlineTime { get; set; }
        public Nullable<System.DateTime> m_MonthlyLastTime { get; set; }
        public Nullable<int> bc_id { get; set; }
        public Nullable<int> l_id { get; set; }
    }
}
